
name: Quality checks

on: [push, pull_request]

env:
  NODE_VER: 20

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node$NODE_VER-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node$NODE_VER-
      - name: Install dependencies (if no cache hit)
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check spelling
        run: npm run spell
      - name: Lint Markdown
        run: npm run lint-md
      - name: Lint Src files
        run: npm run lint
